### ISSUE TITLE
Swagger scala model description missing

### ISSUE THREAD

**Issue by damianbl** [swagger-api/swagger-scala-module#18]
I am using swagger-play2_2.11 (ver. 1.3.12), swagger-scala-module (ver. 1.0.1) and latest swagger-ui in my Scala project. The API method annotations works as expected. The only problem I have is with model annotations. The fields and data types are displayed properly. The only missing thing are descriptions. It does not matter if it is request model or response. It does not work in both cases. The example request model:

```
@ApiModel(description = "Agency booking request")
case class AgencyBookingRequest(@ApiModelProperty(value = "Experience id") experienceId: String,
                            @ApiModelProperty(value = "Number of guests") numberOfGuests: Int,
                            @ApiModelProperty(value = "List of other guests") otherGuests: List[AgencyBookingRequestAccount],
                            @ApiModelProperty(value = "Booking date") date: String,
                            @ApiModelProperty(value = "Booking time") time: String,
                            @ApiModelProperty(value = "Experience price") expectedPrice: Int,
                            @ApiModelProperty(value = "Coupon code") couponCode: Option[String],
                            @ApiModelProperty(value = "Coupon codes") couponCodes: Option[List[String]],
                            @ApiModelProperty(value = "Preferences") preferences: Option[String],
                            @ApiModelProperty(value = "Company id") companyId: String
                           ) extends ExperienceAgencyBookingRequest with IBookingRequest with HasGuestInfo {

}
```

This is how it is annotated on the controller level:

```
 @ApiImplicitParams(Array(
   new ApiImplicitParam(value = "Booking that needs to be created", required = true, dataType = "viewmodels.api.v2.AgencyBookingRequest", paramType = "body")))
```

Have you got any ideas?

Thank you in advance.

**Comment by fehguy** [comment]
Swagger-play 1.3.x and swagger-scala module are simply not compatible.  Can you upgrade to swagger-play 1.5.1?

**Comment by damianbl** [comment]
I thought about it but does swagger-play 1.5.x work with play 2.2.x?
I followed this compatibility info:

https://github.com/swagger-api/swagger-play#compatibility

**Comment by fehguy** [comment]
No, unfortunately you're stuck on 1.3.x unless you go to play 2.4

**Comment by damianbl** [comment]
Can I use any other swagger-scala-module version which would be compatible with 1.3.x?
I suppose no...

**Comment by fehguy** [comment]
you don't need it for 1.3.x, everything is in the dependency.

**Comment by damianbl** [comment]
I removed `swagger-scala-module` dependency and I still do not see model fields description.
