### ISSUE TITLE
Artifact for scala 2.12

### ISSUE THREAD

**Issue by catena2w** [swagger-api/swagger-scala-module#26]
When can we expect release for scala 2.12?

**Comment by pjfanning** [comment]
Swagger-Core is dependent on jackson 2.4.x and does not work properly with jackson 2.8. I think it is a good idea to publish the existing swagger-scala-module code in scala 2.11 and 2.12 compatible jars.
I have a swagger example working with scala 2.12:
https://github.com/pjfanning/swagger-akka-http-sample

I had to use a patched version of swagger-core and I inlined the latest code from swagger-scala-module.

**Comment by svalaskevicius** [comment]
would also be good to see the changes from develop land for 2.11 too :) (all generated properties are shown as optional w/o it)

**Comment by sheinbergon** [comment]
Any updates/progress made in this issue ?

**Comment by fehguy** [comment]
Just pushed 2.10, 2.11, 2.12 support to maven central.
