### ISSUE TITLE
jackson-module-scala 2.8.4

### ISSUE THREAD

**Issue by grzeniokrol** [swagger-api/swagger-scala-module#27]
When can we expect release 1.0.3 with new version of jackson-module-scala 2.8.4?

**Comment by xiaodongw** [comment]
Can we have a new release? I'm looking for the Option support fix (https://github.com/swagger-api/swagger-scala-module/commit/e72beb51509db8ea1c9cbda8a5aa43e70b8e3fe8)

Thanks.

**Comment by fehguy** [comment]
We're close, just got 2.8 jackson issues sorted out in https://github.com/swagger-api/swagger-core/commit/b1cb6b42339f33ec401995f913b83c2e8067cdff

**Comment by fehguy** [comment]
Just pushed 1.0.3 to maven central.  Thanks!
