### ISSUE TITLE
collectionFormat value ignored

### ISSUE THREAD

**Issue by OndrejPacay** [swagger-api/swagger-scala-module#33]
Hi, 

Collection format allows specifying the format of passing URL parameters that allow multiple values.

http://swagger.io/specification/#parameterCollectionFormat

Setting the following annotation on a parameter **someParameter**
` @ApiParam(allowMultiple = true, collectionFormat = "csv", allowableValues = "one,two,three"`
does not change the output swagger definition, the value 'multi' is output:

`{
          "name" : "someParameter",
          "in" : "query",
          "required" : false,
          "type" : "array",
          "items" : {
            "type" : "string",
            "enum" : [ "one", "two", "three" ],
            "default" : "null"
          },
          "collectionFormat" : "multi"
        }`

Version used: 1.0.3

Regards, Ondrej

**Comment by fehguy** [comment]
Please provide a unit test for this if you can.  I don't think this can be limited to just swagger-scala-module, and there are tests in swagger-core for parsing the annotations.

**Comment by OndrejPacay** [comment]
Ok, I will try to create one, thanks.

**Comment by OndrejPacay** [comment]
It seems that I was confused about the responsibilities of each library that my project use and that the problem will be in the play-swagger2 lib. I will close this issue now.

Thanks for the support.
