### ISSUE TITLE
Option[scala.math.BigDecimal] not working as expected

### ISSUE THREAD

**Issue by thepiwo** [swagger-api/swagger-scala-module#34]
Hello, when converting Option[BigDecimal] the output is not as expected, the whole BigDecimal object gets converted. My expectation would be a optional number as BigDecimal converts to number since https://github.com/swagger-api/swagger-scala-module/pull/13.

When debugging the `nextType` passed to `chain.next().resolveProperty(...)` is scala.math.BigDecimal but in `resolveProperty` the `type` will be java.math.BigDecimal after `chain.next()` is called.

I couldn't find a fix for this. When extending `if (cls.isAssignableFrom(classOf[BigDecimal]))` like this `if (cls.isAssignableFrom(classOf[BigDecimal]) || cls.isAssignableFrom(classOf[java.math.BigDecimal]))` the error persists.

**Comment by fehguy** [comment]
Can you please submit a test case so we can reproduce the issue?  A PR would be best.

**Comment by thepiwo** [comment]
Please ignore the first reference, I missed a `git add`.
The PR is https://github.com/swagger-api/swagger-scala-module/pull/35

**Comment by thepiwo** [comment]
Is a release planned the fixes are included in?

**Comment by thepiwo** [comment]
@fehguy what is the status on this? the issue can be closed right?

**Comment by pjfanning** [comment]
@fehguy would it be possible to release 1.0.4? I know you're busy with the OpenAPI upgrades on the core modules but this module is already on its own separate release schedule.

**Comment by fehguy** [comment]
Hi @pjfanning sure, I just pushed 1.0.4.
