### ISSUE TITLE
Cross compile for Scala 2.13.0

### ISSUE THREAD

**Issue by manub** [swagger-api/swagger-scala-module#62]
Scala 2.13.0 has been released, it would be great to publish a cross compiled version.

**Comment by pjfanning** [comment]
https://github.com/swagger-api/swagger-scala-module/pull/63

**Comment by abhamjee** [comment]
Hi, any idea when this will be merged? It is preventing us from upgrading to Scala 2.13. Happy to assist where necessary.

**Comment by pjfanning** [comment]
@abhamjee I have this code in `"com.github.swagger-akka-http" %% "swagger-akka-http" % "1.1.0"` (supports scala 2.13) - you can use that jar instead of this one.

I also have `"com.github.swagger-akka-http" %% "swagger-scala-module" % "2.0.4"` but that only supports swagger 2 / openapi 3

**Comment by gmethvin** [comment]
@webron It looks like we just need to do a release for scala 2.13 now?

**Comment by frantuma** [comment]
2.13.0 added in #63,  version 1.0.6
