### ISSUE TITLE
Option properties are not described correctly, and all properties are being described as optional

### ISSUE THREAD

**Issue by ghost** [swagger-api/swagger-scala-module#7]
A case class property of type `Option[T]` should be represented in the Swagger model as a property of type T; the optional nature of the property would be indicated by `required: false`.

Instead, `Option` is being treated like any other `Iterable` type, so the model appears to have an array property with items of type T— and `required` is _always_ being set to `false`. Properties that are not Options should be assumed to be required (or at least it should be possible to tell Swagger to behave that way, if you're never going to use nulls).

**Comment by fehguy** [comment]
Fixed by #24
