### ISSUE TITLE
Scala primitives inside a List become "Object"

### ISSUE THREAD

**Issue by ghost** [swagger-api/swagger-scala-module#8]
A property of type `List[String]` will be correctly described as an array of strings, but if it's `List[Int]` it'll be described as an array of objects. The same goes for any parameterized type, if the type parameter is a primitive— for instance, when I tried to add support for `Option[T]` (see [issue 7](https://github.com/swagger-api/swagger-scala-module/issues/7)), I found that `Option[String]` worked correctly but `Option[Int]` did not.

This may be a problem with the underlying Jackson Scala module; a comment on [this issue](https://github.com/FasterXML/jackson-module-scala/issues/1) mentioned that Java reflection sometimes misreads Scala primitives as being java.lang.Object. It looked like someone had fixed that in jackson-scala-module, but maybe not. Whatever the reason, it's not currently possible to document a schema that has an array of numbers or booleans in it.

**Comment by ghost** [comment]
A test to reproduce this problem, based on an existing test in `ScalaModelTest` that used a `Vector[String]`:

```
case class ModelWithIntVector (
  ints: Vector[Int]
)

it should "read a model with vector of ints" in {
  val schemas = ModelConverters.getInstance().readAll(classOf[ModelWithIntVector]).asScala
  val model = schemas("ModelWithIntVector")
  val prop = model.getProperties().get("ints")
  prop.isInstanceOf[ArrayProperty] should be (true)
  prop.asInstanceOf[ArrayProperty].getItems.getType should be ("int")  // this fails; it is "object"
}
```

**Comment by fehguy** [comment]
I think it's technically impossible to determine the type of a scala primitive from Java (or scala for that matter).  There's really no other way to do it than use java.lang.Integer for types.  Even `Option[java.lang.Integer]` will work just fine, but I don't think, without depending on a specific version of scalap, that we can interpret `Option[Int]` :(

**Comment by jimschubert** [comment]
I've tested this against the current develop branch (08cd397) and the List passes as and `ArrayProperty` of type `number`:

```diff
diff --git a/src/test/scala/ScalaModelTest.scala b/src/test/scala/ScalaModelTest.scala
index 6321f6b..c75756c 100644
--- a/src/test/scala/ScalaModelTest.scala
+++ b/src/test/scala/ScalaModelTest.scala
@@ -56,8 +56,20 @@ class ScalaModelTest extends FlatSpec with Matchers {
     prop.isInstanceOf[ArrayProperty] should be (true)
     prop.asInstanceOf[ArrayProperty].getItems.getType should be ("number")
   }
+
+  it should "read a model with list of ints" in {
+    val schemas = ModelConverters.getInstance().readAll(classOf[ModelWithIntList]).asScala
+    val model = schemas("ModelWithIntList")
+    val prop = model.getProperties().get("ints")
+    prop.isInstanceOf[ArrayProperty] should be (true)
+    prop.asInstanceOf[ArrayProperty].getItems.getType should be ("number")
+  }
 }
 
+case class ModelWithIntList (
+  ints: List[Int]
+)
+
 case class ModelWithVector (
   name: String,
   friends: Vector[String])
```
